inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
  # TargetRubyVersion: 1.9

# some changes to support older ruby versions
Layout/IndentHeredoc:
  # only works in ruby 2.3+
  EnforcedStyle: unindent
