# commands to time load time
# module_path+=( "/Users/b.caldwell/.zinit/bin/zmodules/Src" )
# zmodload zdharma/zplugin
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
 source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#load shared and 'private' aliases
[[ -f ~/.dotfiles/zsh/aliases ]] && source ~/.dotfiles/zsh/aliases
[[ -f ~/.aliases ]] && source ~/.aliases

[ -f /opt/devctl/devctl.sh ] && \. /opt/devctl/devctl.sh

# with zinit wait these does not work well
# @dfm os=darwin start
if [[ -f $HOME/.iterm2_shell_integration.zsh ]]; then
  source "${HOME}/.iterm2_shell_integration.zsh"

  iterm2_print_user_vars () {
  	# setup kubecontext variable
  	KUBECONTEXT=$(CTX=$(kubectl config current-context) 2> /dev/null;if [ $? -eq 0 ]; then echo $CTX;fi)
  	iterm2_set_user_var kubeContext $KUBECONTEXT
  }
fi

# @dfm end

# Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing DHARMA Initiative Plugin Manager (zdharma/zinit)…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f" || \
        print -P "%F{160}▓▒░ The clone has failed.%f"
fi
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
# End of Zinit installer's chunk

# setopt promptsubst
# zinit snippet $HOME/.dotfiles/zsh/prompt/prompt_benjamin_setup

zinit ice wait lucid multisrc="*.zsh" pick"/dev/null"
zinit light $HOME/.dotfiles/zsh/includes
zinit ice wait lucid multisrc="*.zsh" pick"/dev/null"
zinit light $HOME/.zsh_includes

zinit ice wait lucid atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

zinit ice wait atinit"zpcompinit" lucid
zinit light zdharma/fast-syntax-highlighting

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#424242"
bindkey '[D' autosuggest-accept
